### ISSUE TITLE
Writes the FontForge Python scripts

### ISSUE THREAD

**Issue by 7rs** [7rs/legible-fonts#1]
# ToDo

- ~🤖 To be able to generate the TTF files.~
- ~🤖 To be able to run to completion.~
- ~⚙️ Sets the Python configs.~
- ~⚙️ Sets the Git configs.~
- ~🆎 Places the source fonts.~

## All done.

**Comment by 7rs** [comment]
# How the scripts works

1. Loads the source fonts.
2. Changes glyphs and outputs the sfd file.
3. Merges the SFD files into one.
4. Outputs TTF file.

**Comment by 7rs** [comment]
# ToDo

- [x] ~Loads the source fonts.~
- [x] ~Changes glyphs and outputs the sfd file.~
- [ ] Merges the SFD files into one.
- [ ] Outputs the TTF file.
